### ISSUE TITLE
Feature: Add support for Omemo

### ISSUE THREAD

**Issue by mrbiber** [python-otr/gajim-otr#18]
[Omemo](http://conversations.im/omemo/) is a multi-device, offline-capable implementation of Axolotl.

**Comment by azrdev** [comment]
AIUI omemo is a concurring protocol to OTR, by no means a variant or sth of it. So support should be part of a separate gajim plugin, since it has got nothing to do with gajim-otr besides fulfilling a similar purpose

**Comment by Nebukadneza** [comment]
Hi,

regardless of where, i think that it would be great if gajim could support this. The reason is that gajim, together with conversations (android) is currently the only client supporting a „modern“ set of XEPs, with htt-upload, mam, carbons, inline image display, muc bookmarks, etc. It would be great if omemo — as the encryption standard probably superior to otr(?) — could be added to this list.

I’ve did a bit of digging, and since most people probably don’t want to touch crypto code (i fear it myself!), there seems to be a python implementation using pycrypto:
https://github.com/tgalal/python-axolotl

However, it does need non-python binary libraries, which is probably a problem to ship with gajim plugins(?), right? 

Anyways, even though i’ve never written an gajim plugin, i think i’ll give it a try next week, as is seems like i’ll have some free time :-). Nothing promised though…
Best,
Dario

**Comment by GreenLunar** [comment]
[initial omemo plugin commit](https://trac-plugins.gajim.org/changeset/870b7f3c7c74bd1e78367d6d1a0834efa5217d68/).
