### ISSUE TITLE
Version 1.8?

### ISSUE THREAD

**Issue by sethwoodworth** [python-otr/gajim-otr#20]
My gajim on Arch linux claims that I should update my otr plugin to 1.8 and links to your repository and the upstream [otr cypherpunks page](otr.cypherpunks.ca).  I don't see any reference to version 1.8 here.  Do you know what is going on here?  Or who is maintaining a fork?

**Comment by afflux** [comment]
There is two repositories. This one is the "official" (but unmaintained). Gajim uses a [separate repository](http://hg.gajim.org/gajim-plugins/) to deploy plugins to their plugin installer. Since I'm not actively maintaining this project, I'm not syncing the repositories.

The main gajim dev was asked by users to merge some unreleased commits (3e7d4620 and ca941b0b). He did, and pushed the plugin version to trigger plugin updates.

**Comment by sethwoodworth** [comment]
Thank you for the clarification!
